version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:Z
      - ./db:/docker-entrypoint-initdb.d:z
    networks:
      - dev_net

networks:
  dev_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16